### ISSUE TITLE
Plugin can't find the library

### ISSUE THREAD

**Issue by stonier** [ros-perception/image_common#4]
In an installation from groovy debs, when the plugin gets used it cannot locate the library.

A simple workaround in image_transport/default_plugins.xml on the first line, prefix the path with: '../../'. I'm not sure if this is the 'correct' solution.

See also ros-perception/image_pipeline/issues/1

**Comment by vrabaud** [comment]
This issue has been fixed in the past few days. Can you please mention the version of pluginlib, class_loader and image_common you are using ? thx.

**Comment by stonier** [comment]
Thought it may have been - I noticed the plugins were installing now.

We were using the latest debs
- image_common 1.9.15
- pluginlib 1.8.6

Not sure about class loader?

**Comment by vrabaud** [comment]
pluginlib is at 1.9.3. You probably looked at the fuerte one there.
Can you please try with the latest ? pluginlin 1.9.3 and image_common 1.9.17 : we were able to run image_view and other ones.

Also, what command are you running ?

**Comment by stonier** [comment]
Ah - stupid of me. I completely forgot to beta test turtlebot on the latest debs (shadow-fixed) so we were using 3 week old debs, hence 1.8.6.

I've got shadow-fixed now, with pluginlib 1.9.3 and image_common 1.9.17, nodelet 1.7.7. 

I'm getting a different error now when running image_view (directly or via rosrun).

```
snorri@snorriwork64:/opt/ros/groovy/lib/image_view$ ./image_view
[ WARN] [1352091307.675216276]: Topic 'image' has not been remapped! Typical command-line usage:
        $ rosrun image_view image_view image:=<image topic> [transport]
[ERROR] [1352091308.700416231]: Failed to load nodelet [/image_view_1352091307675093812] of type [image_view/image]: MultiLibraryClassLoader: Could not create object of class type image_view::ImageNodelet as no factory exists for it. Make sure that the library exists and was explicitly loaded through MultiLibraryClassLoader::loadLibrary()
```

Redirecting it as above doesn't work and I'm getting this elsewhere with anything that is a nodelet though, so perhaps need to chase down the problem there.

**Comment by stonier** [comment]
Ok, Ive completely reinstalled from shadow-fixed, also on a second machine and the problem is persisting. Are you successfully running image_view under the same conditions?

**Comment by mirzashah** [comment]
Hey Daniel,
The problem was in class_loader, I accidentally released a buggy version
last night. The fix was pushed and released this morning. Shadow-fixed just
got updated, class_loader is now at 0.1.7. Try that first, I was able to
run rviz fine with the image viewer inside.
-Mirza

**Comment by mirzashah** [comment]
Hey Daniel,
The problem was in class_loader, I accidentally released a buggy version
last night. The fix was pushed and released this morning. My packages just
got updated, class_loader is now at 0.1.7. Try that first, I was able to
run rviz fine with the image viewer inside.
-Mirza

**Comment by jihoonl** [comment]
Hello Mirza,

I have tried to load rviz with new version of class-loader(v 0.1.7) and got these error logs.
Do you have any insight into it?

Jihoon

---

jihoonl@whoolala:~$ rosrun rviz rviz > log

Warning: class_loader::class_loader_core: SEVERE WARNING: A library containing plugins has been opened through a means other than through the class_loader or pluginlib package. This can happen if you build plugin libraries that contain more than just plugins (i.e. normal code your app links against). This inherently will trigger a dlopen() prior to main() and cause problems as class_loader is not aware of plugin factories that autoregister under the hood. The class_loader package can compensate, but you may run into namespace collision problems (e.g. if you have the same plugin class in two different libraries and you load them both at the same time). The biggest problem is that library can now no longer be safely unloaded as the ClassLoader does not know when non-plugin code is still in use. In fact, no ClassLoader instance in your application will be unable to unload any library once a non-pure one has been opened. Please refactor your code to isolate plugins into their own libraries.
         at line 151 in /opt/ros/groovy/include/class_loader/class_loader_core.h
Warning: class_loader::class_loader_core: SEVERE WARNING: A library containing plugins has been opened through a means other than through the class_loader or pluginlib package. This can happen if you build plugin libraries that contain more than just plugins (i.e. normal code your app links against). This inherently will trigger a dlopen() prior to main() and cause problems as class_loader is not aware of plugin factories that autoregister under the hood. The class_loader package can compensate, but you may run into namespace collision problems (e.g. if you have the same plugin class in two different libraries and you load them both at the same time). The biggest problem is that library can now no longer be safely unloaded as the ClassLoader does not know when non-plugin code is still in use. In fact, no ClassLoader instance in your application will be unable to unload any library once a non-pure one has been opened. Please refactor your code to isolate plugins into their own libraries.
         at line 151 in /opt/ros/groovy/include/class_loader/class_loader_core.h
[ERROR] [1352246890.731977368]: Attempting to create unmanged instance...
[ERROR] [1352246890.732051706]: Loading library for class rviz/Orbit...
[ERROR] [1352246890.803168398]: Attempting to create instance through low level multi-library class loader.
[ERROR] [1352246890.861010455]: Attempting to create unmanged instance...
[ERROR] [1352246890.861092189]: Loading library for class rviz/MoveCamera...
[ERROR] [1352246890.907314473]: Attempting to create instance through low level multi-library class loader.
[ERROR] [1352246890.922941362]: Attempting to create unmanged instance...
[ERROR] [1352246890.922987712]: Loading library for class rviz/Interact...
[ERROR] [1352246890.974318660]: Attempting to create instance through low level multi-library class loader.
[ERROR] [1352246890.986012206]: Attempting to create unmanged instance...
[ERROR] [1352246890.986058403]: Loading library for class rviz/Select...
[ERROR] [1352246891.033708099]: Attempting to create instance through low level multi-library class loader.
[ERROR] [1352246891.046022805]: Attempting to create unmanged instance...
[ERROR] [1352246891.046061854]: Loading library for class rviz/SetInitialPose...
[ERROR] [1352246891.096293768]: Attempting to create instance through low level multi-library class loader.
[ERROR] [1352246891.115711275]: Attempting to create unmanged instance...
[ERROR] [1352246891.115748231]: Loading library for class rviz/SetGoal...
[ERROR] [1352246891.161085351]: Attempting to create instance through low level multi-library class loader.

**Comment by mirzashah** [comment]
Hey Jihoon,
Those errors are a misuse of ROS_ERROR instead of ROS_DEBUG. The issue is
in pluginlib, I released a new version a few minutes ago -- it'll be a few
hours before the .debs are ready.
-mas

**Comment by stonier** [comment]
Cool - successfully got rviz image plugin showing images here as well. Still have a problem with 'rosrun image_view image_view' though. Same error as mentioned above.

**Comment by mirzashah** [comment]
I had issues with rosrun with overlaid catkin projects myself today...I ran
rviz and image_viewer directly without rosrun. I'll check it out tomorrow
and see if I can shed some light on it. -mas

**Comment by stonier** [comment]
Seems to be fixed. I'll check again on Monday at work and see if I can create problems with it again and close the issue if it's ok.

**Comment by vrabaud** [comment]
@stonier : is that fixed for you. Should that bug be closed ?

**Comment by stonier** [comment]
@vrabaud Just tested with uvc_camera and image_view, bonza.
